name: 'A Testing Environment for Problem Solvers'
description: 'Checks whether a Code which is Pushed, passed all the test cases or not for a particular Problem'
runs:
  using: 'node12'
  main: 'index.js'
